### PR TITLE
Adding AverageShape to daops

### PR DESCRIPTION
**Pull request by charlesgauthier-udm**
### Pull Request Checklist:
- [~] This PR addresses an already opened issue (for bug fixes / features)
    - This PR is related to this [issue](https://github.com/ESGF/esgf-cwt/issues/30) and is the continuation of this [PR](https://github.com/roocs/clisops/pull/312) 
- [X] Tests for the changes have been added (for bug fixes / features)
- [X] Documentation has been added / updated (for bug fixes / features)
- [X] HISTORY.rst has been updated (with summary of main changes)
- [X] I have added my relevant user information to `AUTHORS.md`

* **What kind of change does this PR introduce?:** 
This PR adds the Spatial Averager operator to daops allowing to perform an average over a specified region

* **Does this PR introduce a breaking change?:** 
Not to my knowledge

* **Other information:** 
As it is, the `shape` parameter required by `AverageShape` is similar to the freq parameter of `AverageTime` in that it is only defined using the inputed argument. For the averqage across dimensions (`Average`), the `dims` parameter is defined as a `dimension_parameter` coming from `roocs_utils`. I was not sure if it was needed to add a `shape_parameter` to `roocs_utils ` so I left it as is. If you feel like that would be preferable , please mention it in the PR and I'll add a `shape_parameter` to `roocs_utils`.

### CODE REVIEW

**Comment by cehbrecht** [comment]
> * For the averqage across dimensions (`Average`), the `dims` parameter is defined as a `dimension_parameter` coming from `roocs_utils`. I was not sure if it was needed to add a `shape_parameter` to `roocs_utils ` so I left it as is. If you feel like that would be preferable , please mention it in the PR and I'll add a `shape_parameter` to `roocs_utils`

@charlesgauthier-udm If the `dimension_parameter` works I would keep it. We want to move `roocs_utils` into `clisops`. We could refactor `roocs_utils` when it has moved.

**Comment by cehbrecht** [comment]
@charlesgauthier-udm tests are failing due to a new intake version. Do you like to add a restriction for intake within this PR?
https://github.com/roocs/rook/blob/b5c53321179c3fdfc97ae115798f09658daacbab/environment.yml#L32 

... otherwise I will open a new PR to fix this.

**Comment by charlesgauthier-udm** [comment]
> @charlesgauthier-udm tests are failing due to a new intake version.
Since the failing tests are not related to the polygon subsetting, I would suggest opening another PR, but if you don't have the time I can limit intake to 0.7.0 in this PR which seems to be working.

**Comment by cehbrecht** [comment]
> > @charlesgauthier-udm tests are failing due to a new intake version.
> 
> Since the failing tests are not related to the polygon subsetting, I would suggest opening another PR, but if you don't have the time I can limit intake to 0.7.0 in this PR which seems to be working.

@charlesgauthier-udm I will open a new PR for the intake issue :)

**Review by cehbrecht — APPROVED** [review]

**Comment by cehbrecht** [comment]
@charlesgauthier-udm I can merge if this PR is ok for you.

**Comment by charlesgauthier-udm** [comment]
Yes, all good thank you for your review.

**Pull request merged**
